# Name of Configuration and Experiment Mode.
name: "CodeClassificationConfig"
task: "CodeClassification"
model_type: "GAT"
task_type: "Classification"
classify_mode: "Multi-class"

# Vocabulary Setting
token_vocab_path: "./data/poj104/token_vocab_dict.pkl"
node_vocab_path: "./data/poj104/node_vocab_dict.pkl"

# Dataset Specification Configuration
dataset:
  name: "online-judge"
  path: "./data/poj104/"

# General Configuration
output_path: "./trained_model/code_classification/gat"
use_cuda: True
disable_tqdm: True
class_weight: True
initial_test: False
save_output: True
use_scheduler: True
mm_var: "weighted_accuracy" # Main Monitor Variable/Main Metric Variable
monitor_vars: ["weighted_accuracy"]
gpu_id: 0

# General Configuration
max_code_token_len: 20
class_num: 104
optimizer_type: ADAM
lr: 0.01
batch_size: 128
max_epoch: 50
patience: 10
word_emb_dims: 128
dropout: 0.2

# Node Embedding Layer
node_emb_layer:
  mode: "LSTMEmbedNode" # Average/LSTM/MLP
  dims: 128
  layers: 1
  use_nfeature: "both" # structure or textual or both

# GAT Parameters
gat:
  in_dim: 128
  out_dim: 128
  layers: 1
  nhead: 8
  dropout: 0.2



