# Name of Configuration and Experiment Mode.
name: "CodeClassificationConfig"
task: "CodeClassification"
model_type: "GGNN"
task_type: "Classification"
classify_mode: "Multi-class"

# Vocabulary Setting
token_vocab_path: "./data/poj104/token_vocab_dict.pkl"
node_vocab_path: "./data/poj104/node_vocab_dict.pkl"

# Dataset Specification Configuration
dataset:
  name: "online-judge"
  path: "./data/poj104/"

# General Configuration
output_path: "./trained_model/code_classification/ggnn"
use_cuda: True
disable_tqdm: True
class_weight: True
initial_test: False
save_output: True
use_scheduler: True
mm_var: "weighted_accuracy" # Main Monitor Variable/Main Metric Variable
monitor_vars: ["weighted_accuracy"]
gpu_id: 0

# Generic Model Hyperparameters
max_code_token_len: 20
class_num: 104
optimizer_type: ADAM # SGD, ADAMW, ADAMAX, ADAM
lr: 0.001
batch_size: 128
max_epoch: 50
patience: 10
word_emb_dims: 128
dropout: 0.2
self_loop: True
reverse_edge: True
use_edge_type: cpg # ast, cfg, cdg, ddg, and cpg


# Node Embedding Layer
node_emb_layer:
  mode: "LSTMEmbedNode" # AverageEmbedNode/LSTMEmbedNode/MLP
  dims: 128
  layers: 1
  use_nfeature: "distinct-feats" # structure or textual or both-full-textual or both-id-textual


# GGNN Parameters
ggnn:
  initial_representation: True
  in_dim: 128
  out_dim: 128
  nsteps: 4
  dropout: 0.2
  graph_agg: max # sum, mean, max






